#!/usr/bin/env python3
from __future__ import annotations

import sys

if len(sys.argv) > 1 and sys.argv[1] == "gui":
    from fzztool.gui import launch
    launch()
else:
    from fzztool.cli import main
    raise SystemExit(main(sys.argv[1:]))
